config/routes.rb
Bucketlist::Application.routes.draw do

  resources :comments
  resources :destinations
  resources :to_do_items do
  member do
       post :like
       post :comment
   end
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :to_do_item_id
  belongs_to :to_do_item
end

app/models/destination.rb
class Destination < ActiveRecord::Base
  attr_accessible :name
  has_many :to_do_items
end

app/models/like.rb
class Like < ActiveRecord::Base
  attr_accessible :to_do_item_id, :user_id
  belongs_to :user
  belongs_to :to_do_item
end

app/models/to_do_item.rb
class ToDoItem < ActiveRecord::Base
  attr_accessible :completed, :name, :location, :latitude, :longitude, :destination_id
  has_many :likes
  # validates :location, :presence => true

  # geocoded_by :my_cool_geocoding_method
  #name of the method
  # after_validation :geocode
  #make sure that the name and location are there and then puts the location co-ordinates into longitude and latitude
  has_many :comments
  belongs_to :destination
  belongs_to :user
  has_many :users, :through => :likes

  # def my_cool_geocoding_method
  # 	"#{self.location} #{destination.name}"
  # end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name
  has_many :likes
  has_many :my_to_do_items, :class_name => 'ToDoItem'
  has_many :liked_items, :through => :likes, :class_name => 'ToDoItem'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

	def index 
		@comments = Comment.all
	end

	def new
		@comment= Comment.new
	end

	def create
		# binding.pry
		@comment = Comment.new(params[:comment])
		@comment.save!
		render @comment
    end
    

end

app/controllers/destinations_controller.rb
class DestinationsController < ApplicationController
	# def index
	# end

	def new
	end

	def create
		# binding.pry
		@destination_id = params['searchid']
		# binding.pry
		@destination = Destination.where(id:@destination_id)
		#there are two destinations here, it is going to render the template twice
		# binding.pry
		render :template => 'destinations/create', :content_type => 'text/javascript'
		end
		  # binding.pry
	# 	end
	# end
end

app/controllers/to_do_items_controller.rb
class ToDoItemsController < ApplicationController
	def index 
		@to_do_items = ToDoItem.all
		@destinations = Destination.all
		@comments = Comment.all
	end

	def new
		@to_do_item = ToDoItem.new
	end

	def show 
		@to_do_item = ToDoItem.find(params[:id])
	end

	def create
		
		@to_do_item = ToDoItem.create(params[:to_do_item])

        respond_to do |format|
            if @to_do_item.save
              format.html { redirect_to @to_do_item, notice: 'User was successfully created.' }
              # binding.pry
              format.js   {}
              #This goes to the create.js.erb
              format.json { render json: @to_do_item, status: :created, location: @to_do_item }
            else
              format.html { render action: "new" }
              format.json { render json: @to_do_item.errors, status: :unprocessable_entity }
            end
          end

	end



   def like
   	@to_do_item = ToDoItem.find(params[:id])
   	@user = User.find(1)
   	@like = Like.create(:to_do_item_id => @to_do_item.id, :user_id => @user.id)

    respond_to do |format|
          if @like.save
            format.html { redirect_to @to_do_item, notice: 'User was successfully created.' }
            # binding.pry
            format.js   do 
              @item_id = params[:id]
            end
            #This goes to the create.js.erb
            format.json { render json: @to_do_item, status: :created, location: @to_do_item }
          else
            format.html { render action: "new" }
            format.json { render json: @to_do_item.errors, status: :unprocessable_entity }
          end
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/destinations_helper.rb
module DestinationsHelper
end

app/helpers/to_do_items_helper.rb
module ToDoItemsHelper
end

app/views/comments/_comment.html.erb
<div class = "comment" data-item-id="<%=comment.to_do_item_id%>">
  <h5> <%=comment.body%> </h5>
</div>

app/views/comments/_form.html.erb
  <div class="extend-form">
     <h4>Click to create a comment</h4>
  </div>

 <div class="extendible-form">
 
    	<%= form_for Comment.new(:to_do_item_id => item.id), :remote => true do |f| %>

        <%= f.hidden_field :to_do_item_id %>

        <div class="field" id='clearsearch' value=''>
        	  <%= f.text_area :body %>
        </div>

        <div class="field">
        	 <%= f.submit %>
        </div>

     <% end %>
 </div>

app/views/comments/index.html.erb
<h1>To do list </h1>

<% @comments.each do |x| %>
    <br><%= x.body%></br>
<% end %>

app/views/destinations/_destination.html.erb
<div class="encapsulated">

<div class="destinations">
	<h1><%= destination.name %></h1>

	<div class="searchbox">
	   <input type="text" id="search" placeholder="Search a To Do Item">
	</div>

</div>

<div class="destination">
   <div class="todoitemsearch"> 
		<div class = "todoitem<%=destination.id%>">

		<% destination.to_do_items.each do |to_do_item| %>
		    <h4><%= render to_do_item, :item_id=>to_do_item.id %></h4>
		<% end %>
	    </div>
   </div>

     <div class = "addtodoitem">
    <%= render :partial => 'to_do_items/form', :locals => {:destination_id => destination.id} %>
    </div>
 </div>

</div>

app/views/destinations/create.js.erb
$('#appenditems').html("");
$('#appenditems2').html("");
<% @destination[0].to_do_items.each do |to_do_item| %>
  <%#binding.pry%>
  <%#=to_do_item.id%>
  $('#appenditems').append('<%= j(render to_do_item, :locals => {:to_do_item=>@to_do_item}) %>');
   
   // initmap();
   addMarker(<%=to_do_item.latitude%>, <%=to_do_item.longitude%>, '<%=to_do_item.name%>');

<%end%>
<%#binding.pry%>

<%#div class = "addtodoitem"%>
  $('#appenditems2').append('<%= j(render :partial => 'to_do_items/form', :locals => {:destination_id => @destination[0].id}) %>');
// </div>
<%#end%>


// $('.destinations').click(function(){
//   $('.destinations').hide();
//   // $('#style').show();
// //   var destination = $('<div>').addClass('jsdestination').html('<%#=@destination[0].name%>');
// //   // destination.setAttribute('class', 'jsdestination');
// //   $('.appenditems').append(destination);
// //   // destination.setAttribute('class', 'jsdestination');
// //   // var to_do_item = '<%#=@tdiarray%>'
// //   // var to_do_item = to_do_items.to_a
// //   <%#binding.pry%>

// //   $.each(<%#=raw @tdiarray.to_json%>, function(index, value){
// //   	specto_do_item = $('<div>').addClass('jsto_do_item').html(value);
// //   	$('.appenditems').append(specto_do_item);
// //       // alert(index + ': ' + value);
// //   });
// });
// <div class="todoitemsearch"> 
// <%#@destinations.each do |destination|%>
// <div class = "todoitem<%#=destination[0].id%>">

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bucketlist</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

<div class="googlemaps">

  <script type = "text/javascript" src= "https://maps.googleapis.com/maps/api/js?key=AIzaSyC74gnSe7p17ulcZUzgPJHxYurGg2bjRYg&sensor=false">
  </script>

  
  <script type="text/javascript">

      $(function() {
      initMap();

      //add here var items that converts ToDoItems to JSON, take out the var to make to global
      items = <%= raw(ToDoItem.all.to_json) %>
      console.log(items);

      <% ToDoItem.all.each do |item| %>
      addMarker(<%=item.latitude%>, <%=item.longitude%>, '<%=item.name%>');
      <%end%>
     });
  </script>
</div>
     
</head>
<body>

<%= yield %>

</body>
</html>















   

app/views/to_do_items/_form.html.erb
<div class ="to_do_form">
  <h3>Create a new to do item</h3>

<%= form_for ToDoItem.new(:destination_id => destination_id) , :remote => true do |f| %>

  <%= f.hidden_field :destination_id %>

    <p>Name</p> <BR>
  	  <%= f.text_field :name %>

    <p>Location</p>
  	  <%= f.text_field :location %>

  	 <%= f.submit %>

  <% end %>

</div>


  

app/views/to_do_items/_like.html.erb
<div class ="like" value="<%=to_do_item.id%>" data-destination-id="<%=to_do_item.destination_id%>">
	<%=@to_do_item.name%>
    <%=@user.name%>
</div>

app/views/to_do_items/_like.js.erb
$('.name').append("<%= escape_javascript(@user.name + 'likes' + @to_do_item.name) %>");

app/views/to_do_items/_newtodoitem.html.erb
<div class="newtodoitem" data-item-id="<%=@to_do_item.destination_id%>">
	
  <h5> <%=@to_do_item.name%> </h5>
</div>

app/views/to_do_items/_to_do_item.html.erb
<div class="to_do_item <%= to_do_item.completed? ? 'completed' : '' %>">

  <div class="name" data-item-id="<%=to_do_item.destination.id%>">
   <h3><%= to_do_item.name%></h3>
 </div>

  <div class="likeimage">
    <%=link_to image_tag('like.jpg', :width => 20),like_to_do_item_path(to_do_item.id), :remote => true, :method => :post %>

    <div id="update<%=item_id%>" style="display:inline-block;">
      <%= "#{pluralize(to_do_item.likes.count,'like')}" %>
    </div>
  </div>

 <div id="style" class="comments<%=to_do_item.id%>">
   <% to_do_item.comments.each do |comment| %>
    <%= render comment %>
  <% end %>

 </div>

 <%= render :partial => 'comments/form', :locals => { :item => to_do_item } %>

</div>

app/views/to_do_items/create.js.erb
var div = document.createElement('div');
var tditem = ("<%= j(@to_do_item.name) %>");
div.innerHTML = tditem;
$('.to_do_item').append(tditem);

//I need to append another erb template onto the form as I did in Blogosphere, this is a bit hard right now, going to explore the appl further; 

app/views/to_do_items/index.html.erb
<div class="title">
	<h1>My Bucket List </h1>
</div>

<div id="map-canvas">
</div>

<div id="wholedoc">

	<div class= "main" id="style">
		<% @destinations.each do |destination| %>

			<div class="destinations">
				<h1><%= destination.name %></h1>
			</div>

        	<div class="bodyslidetoggle">
				<input type="text" id="search" placeholder="Search a To Do Item">
			</div>

			<div class="destination">
				<div class = "todoitem<%=destination.id%>">
					<% destination.to_do_items.each do |to_do_item| %>
					<h4><%= render to_do_item, :item_id => to_do_item.id %></h4>
					<% end %>
				</div>

				<div class = "addtodoitem">
					<%= render :partial => 'to_do_items/form', :locals => {destination_id: destination.id} %>
				</div>
			</div>
		<% end %>
	</div>

</div>

app/views/to_do_items/like.js.erb
$('#update<%=j @item_id%>').html("<%=j link_to image_tag('like.jpg', :width => 20), :remote=>true;  "#{pluralize(@to_do_item.likes.count,'like')}" %>")



 

app/views/to_do_items/newindex.html.erb
<div class= "main" id="mathilda">
	  <%# @destinations.each do |destination| %>
	    <div class="destinations" id='<%=destination[0].id%>' data-destination-id="<%=destination[0].id%>">
		  <h2><%=destination.name%></h2>
		</div>
	  <%#end%>
    </div>

	<div class="todoitemsearch"> 
	  <%#@destinations.each do |destination|%>
	    <div class = "todoitem<%=destination[0].id%>">
		  <% destination[0].to_do_items.each do |to_do_item| %>
			<h4><%= render to_do_item, :item_id=>to_do_item.id %></h4>
		  <%#end%>
		</div>
	</div>

	<div class = "addtodoitem">
		<%= render :partial => 'to_do_items/form', :locals => {:destination_id => destination[0].id} %>
	</div>
  <%end%>
</div> 